_wandb:
    value:
        cli_version: 0.23.1
        e:
            e3poz2hwfsmy3h6oajoevhjln0ocfol3:
                codePath: /workspace/hf_llm/notebooks/ch3f.ipynb
                codePathLocal: ch3f.ipynb
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "32212254720"
                        used: "763715584"
                email: tensor.polinomics@gmail.com
                executable: /workspace/hf_llm/.venv/bin/python
                git:
                    commit: 85ef87496633f06ac73d2d9cb130e1af9a78d3f5
                    remote: https://github.com/tensor-polinomics/hf_llm.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-ed25543f-29c8-68d7-a84f-8610b6873baa
                host: a2cea6cc2e34
                memory:
                    total: "540821815296"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.39
                program: /workspace/hf_llm/notebooks/ch3f.ipynb
                python: CPython 3.12.3
                root: /workspace/hf_llm/notebooks
                startedAt: "2025-12-08T02:06:42.516068Z"
                writerId: e3poz2hwfsmy3h6oajoevhjln0ocfol3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "3":
                - 2
                - 13
            "4": 3.12.3
            "5": 0.23.1
            "6": 4.57.3
            "8":
                - 1
            "12": 0.23.1
            "13": linux-x86_64
